stages:
  - compile

compile:
  image: ubuntu:22.04
  before_script:
    - apt-get update && apt-get install -y make gcc-avr avr-libc avrdude
  stage: compile
  script: 
  - make hex
  rules:
  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'